test.lo: /root/workspace/php/ext/test/test.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/workspace/php/ext/test $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/workspace/php/ext/test/test.c -o test.lo 
$(phplibdir)/test.la: ./test.la
	$(LIBTOOL) --mode=install cp ./test.la $(phplibdir)

./test.la: $(shared_objects_test) $(TEST_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_test) $(TEST_SHARED_LIBADD)

